@startuml flexeat-uml
skinparam linetype ortho

package state {
    class DishState {
        +editing: bool
        +ingredients: List<FilledIngredient>
    }

    class ProductState {
        +editing: bool
        +nutritionFacts: NutritionFacts
        +packagings: List<PackagingStats>
        +compatibleArticles: List<String>
    }

    class FilledIngredient {
        +articleName: String
        +weight: int
        +productName: String
        +packagingWeight: int
        +nutritionFacts: NutritionFacts
        +cost: int
    }

    class ListedProduct {
        +productName: String
        +packagingWeight: int
        +nutritionFacts: NutritionFacts
    }

    class PackagingStats {
        +weight: int
        +lastPrice: int
    }

    DishState --* FilledIngredient
    ProductState --* PackagingStats
}

package presentation {
    class DishesListCubit {
        +state: List<Dish>
    }

    class DishCubit {
        +state: DishState
    }

    class ProductsListCubit {
        +state: List<ListedProduct>
    }

    class ProductCubit {
        +state: ProductState
        +edit(): void
        +save(): void
        +setName(name: String): void
        +reportPrice(price: int): void
        +addPackaging(weight: int): void
    }
    
    DishCubit --o DishState
    ProductsListCubit --o ListedProduct
    ProductCubit --o ProductState
}

package domain {
    entity NutritionFacts {
        +calories: int
        +proteinsPercent: int
    }
    
    entity Dish {
        +name: String
    }
}

DishesListCubit --o Dish
ProductState --o NutritionFacts
@enduml