name: flexeat
description: Flexible recipes and food budget planning

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  flutter_bloc: ^8.0.0
  google_fonts: ^2.3.2
  provider: ^6.0.2
  sqflite: ^2.0.2+1
  path: ^1.8.1
  kiwi: ^4.0.2
  auto_route: ^4.0.0
  reactive_forms: ^13.0.0
  flutter_typeahead: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.3
  mockito: ^5.1.0
  build_runner: ^2.1.10
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true
